In [ ]:
import numpy as np


# what is numpy 

# why use numpy 


In [15]:
data = [1,2,3,4,5,6,7]

In [18]:
data = np.array(data)

In [19]:
print(data)

[1 2 3 4 5 6 7]


In [20]:
type(data)

numpy.ndarray

In [13]:
data.ndim

1

In [21]:
data.dtype

dtype('int32')

In [22]:
print(len(data))

7


In [23]:
data.size

7

In [24]:
data.shape

(7,)

In [25]:
data

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
data[1:5:1]

array([2, 3, 4, 5])

# 1D array

In [31]:
D1 = np.array([1,2,3])

print(D1)

print(D1.ndim)

print(D1.size)

print(D1.shape)

print(D1.dtype)

[1 2 3]
1
3
(3,)
int32


# 2D array 

In [38]:
D2 = np.array([[22,33,44],[45,67,78],[67,87,45],[34,67,98]])


print(D2)

print(D2.ndim)

print(D2.size)

print(D2.shape)

print(D2.dtype)

[[22 33 44]
 [45 67 78]
 [67 87 45]
 [34 67 98]]
2
12
(4, 3)
int32


# 3D array

In [39]:
D3 = np.array([[[12,45,67],[45,67,89]]])

In [47]:
print(type(D3))

print(D3.ndim)

print(D3.size)

print(D3.shape)

print(D3.dtype)

<class 'numpy.ndarray'>
3
6
(1, 2, 3)
int32


# Function 

In [48]:
data = [22,45,67,8,9,99,89,56,45,34,23,12,67]

In [49]:
data = np.array(data)

In [50]:
data

array([22, 45, 67,  8,  9, 99, 89, 56, 45, 34, 23, 12, 67])

In [51]:
data.max()

99

In [52]:
data.min()

8

In [53]:
D = np.array([2,4,6])

B = np.array([1,2,4])


T = D+B
print(T)

[ 3  6 10]


In [54]:
Y = D * D

print(Y)

[ 4 16 36]


In [55]:
U = D * 2 

print(U)

[ 4  8 12]


In [57]:
Avg = data.mean()

In [59]:
Avg = int(Avg)

print(Avg)

44


In [66]:
count_of_data = data.size

count_of_data

13

In [64]:
sum_of_data = sum(data)

In [67]:
Avg_2 = sum_of_data / count_of_data

print(f"{Avg_2}  ------ {Avg}")

44.30769230769231  ------ 44
